### ISSUE TITLE
Should we archive this repo as read-only?

### ISSUE THREAD

**Issue by raghavendra-talur** [gluster/samba-glusterfs#2]
This repo needs to be deprecated. Gluster plugin for Samba is in Samba main repo.  This repo was created because we wanted to maintain a version of plugin for 3.6 branch of Samba. Do we still need to do that?

**Comment by jarrpa** [comment]
Agreed, we don't need to maintain this and really don't maintain this anymore.

**Comment by jarrpa** [comment]
Unfortunately, there's no such setting in Github. Seems the best we can do is just note in the description that this is no longer maintained. I'll update the README too.
